### ISSUE TITLE
Implement execution of serialized scripts

### ISSUE THREAD

**Issue by ergomorphic** [ScorexFoundation/sigmastate-interpreter#109]
We may want to parameterise ErgoScript with another script, given as serialised `Array[Byte]`.
However we cannot allow user to manipulate script bytes, so we cannot just provide generic `execute[T](bytes)` function because it will be impossible to implement `cost` function in general case.
Actual script representation should be hidden from the user.
However we can assume that some Context variables and Box registers may be executed as scripts, which may look like this
```
let x = execute[Int](24)  // execute context variable 24 as script returning Int
let y = box.executeRegister[Boolean](5)
```
The location of script bytes is different in these cases, but the execution procedure in similar.
Execution is performed before cost estimation and have the following steps:
1. Deserialize bytes to Value[T] for some T, which become known after deserialization
2. Check that T is equal to parameter type (Int or Boolean in the examples above)
3. Insert deserialized tree instead of function invocation

Subtasks:
- [ ] add class ExecuteContextScript 
- [ ] implement `execute` as global function
- [ ] add class ExecuteRegisterScript
- [ ] implement `executeRegister` as method of Box

**Comment by ergomorphic** [comment]
Implemented as `DeserializeContext` and `DeserializeRegister` operations.

**Comment by aslesarenko** [comment]
Closing in favor of #407
