### ISSUE TITLE
Implement Downcast conversion operation for integer types

### ISSUE THREAD

**Issue by ergomorphic** [ScorexFoundation/sigmastate-interpreter#147]
- [ ] introduce Downcast IR node similar to Upcast but in reverse direction with overflow checks
- [ ] replace IntToByte, etc with Downcast

**Comment by greenhat** [comment]
@ergomorphic What's the syntax for downcast should be?

1. `5.toByte`, `5.toLong`, etc.
2. `downcast(5, Byte)`, etc.
3. `intToByte(5)`, `intToLong(5)`, etc.

I like the first option, but the third option would probably be the easiest to implement.

**Comment by ergomorphic** [comment]
@greenhat Actually the easiest is 1), but it needs to do an experiment first with `SNumericType`.
`trait SNumericType extends SType`
Try to do `trait SNumericType extends SProduct` and see which tests fail.
If none, than you can add necessary methods to SShort, SInt, SLong, etc.
