### ISSUE TITLE
Upcast function arguments of numeric type

### ISSUE THREAD

**Issue by ergomorphic** [ScorexFoundation/sigmastate-interpreter#151]
See "map + sum" test. The literal `20` is automatically upcasted to Long, this is implemented, but `0L` is not.

**Comment by greenhat** [comment]
@ergomorphic Could you give more details? I'm not sure I get the idea. I've looked into the `map + sum` test and nothing caught my eye.

**Comment by aslesarenko** [comment]
@greenhat this `outValues.fold(0L, { (x: Long, y: Long) => x + y })` should be possible to rewrite like this `outValues.fold(0, { (x: Long, y: Long) => x + y })`
Note `0` literal in a Long position

**Comment by jozanek** [comment]
I would suggest to close this ticket as even scala compiler throws an error:
```
scala> List(1,2,3).fold(0)((x: Long, y: Long) => x+y)
-- [E007] Type Mismatch Error: -------------------------------------------------
1 |List(1,2,3).fold(0)((x: Long, y: Long) => x+y)
  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  |                    Found:    (Long, Long) => AnyVal
  |                    Required: (AnyVal, AnyVal) => AnyVal
```

**Comment by aslesarenko** [comment]
yes, good point.
