### ISSUE TITLE
Optimize represenation and serialization of multiple AND/OR

### ISSUE THREAD

**Issue by catena2w** [ScorexFoundation/sigmastate-interpreter#154]
script `true && true && true` should be decoded do `AND(TrueLeaf, TrueLeaf, TrueLeaf)`, now it is decoded to `AND(AND(TrueLeaf, TrueLeaf), TrueLeaf)`.
Test created in https://github.com/ScorexFoundation/sigmastate-interpreter/pull/146

**Comment by ergomorphic** [comment]
@catena2w this is correct behavior.
&&, || - are binary left-associative operations
`AND(TrueLeaf, TrueLeaf, TrueLeaf)` can be constructed using `allOf(Array(true, true, true))
