### ISSUE TITLE
Avoid serializing conversion Upcast nodes

### ISSUE THREAD

**Issue by ergomorphic** [ScorexFoundation/sigmastate-interpreter#164]
Reduce serialization size of the scripts by not serializing conversion Upcast nodes, because they can be automatically added as necessary during deserialization.

Considerations for implementation:

Type checking during deserialization should work in the following way.

1. We can think about it as having kind of 'smart constructor' for each IR node, which is used instead of direct construction of the nodes.
2. Each 'smart constructor' checks typing constraints before constructing the node and throws an exception in the case of violations.
3. Deserializer never construct nodes directly using standard constructor.
Thus at the end we obtain an IR which satisfies the set of constraints placed in smart constructors.

4. An observation is that in deserializer we expect the arguments of smart constructors should be valid. This is in contrast to SigmaTyper, where we expect the original tree is partially typed.

5. The 'checking' part of the smart constructors should be decoupled from 'constructing' part.

6. It make sense to collect all the smart constructors in a separate interface SigmaBuilder.
7. We can have two implementations of SigmaBuilder: 1) doing just constructions 2) doing checking and then constructing nodes.
8. Decoration by subclassing can be used to create specialized builders.
9. Deserializer should work up to SigmaBuilder interface.

**Comment by greenhat** [comment]
@ergomorphic Who is responsible for making an actual upcast on deserialization? I suppose that should be the smart constructor, but 2. says it should throw an exception. Or does it mean that it first tries to satisfy the constraints via transformation application (upcast, etc.) and if it fails then an exception is thrown?

If the above assumption is correct can we do something with the duplication of transformation application logic? Both typer and smart constructor would implement an upcast application. Is it worth considering code reuse? We can consider using smart constructors in the typer, or extract a "sub-typer" phase and use it in smart constructors somehow.

**Comment by ergomorphic** [comment]
@greenhat The key points here is be both efficient and modular. Which seems like contradicting requirements. :) 
We should avoid transformations during deserialization.
We can implement SigmaBuilders using `stackable traits` pattern in Scala.
```
trait SigmaBuilder { def EQ(...): Value[SBoolean.type] }
class StdSigmaBuilder { override def EQ(...) = new EQ(...) }
trait CheckingSigmaBuilder { 
  override def EQ(...) = { if (!constrainCheck(...)) throw ...;  super.EQ(...) } 
}
class DeserializationSigmaBuilder extends StdSigmaBuilder with CheckingSigmaBuilder
```
thus we can both reuse code, and configure builder as we need in concrete case

**Comment by greenhat** [comment]
@ergomorphic Thanks for the code snippet. I've made a new PR #188 with `EQ` node as an example. 
I've put upcast application login into `TransfrormingSigmaBuilder` and designated it to be `DeserializationSigmaBuilder` and leave strict constraint check in `CheckingSigmaBuilder`.
