### ISSUE TITLE
Deserialization already checks if g, h, u, v are in the group

### ISSUE THREAD

**Issue by reyzin** [ScorexFoundation/sigmastate-interpreter#168]
https://github.com/ScorexFoundation/sigmastate-interpreter/blob/df7414177994ece733f55ec0e8b42da111dd46c5/src/main/scala/sigmastate/interpreter/Interpreter.scala#L401 This line says that we should check if g, h are in the group. However, deserialization, which goes through bouncyCastle's [decodePoint](https://github.com/bcgit/bc-java/blob/master/core/src/main/java/org/bouncycastle/math/ec/ECCurve.java#L364) already does that.  So there's no need to check as long as the values come to the verifier through deserialization. But we should probably write some tests to make sure that deserialization fails on points that are not group elements, in case bouncycastle messes up in future releases?

Also, to be consistent, whatever we do for DiffieHellman (g, h, u, v) we should also do for Schnorr's h.

Caveat: if the curve has a cofactor, then bouncycastle will NOT check that the point is in the prime-order subgroup -- only that it's on the curve. It has a check called "[satisfiesCofactor](https://github.com/bcgit/bc-java/blob/master/core/src/main/java/org/bouncycastle/math/ec/ECPoint.java#L67)" but that check doesn't actually do what you would expect it to do. It's unclear what the intent of "satisifiesCofactor" is. Perhaps we should report this issue to bouncyCastle.

**Comment by kushti** [comment]
After a lot of considerations, secp256k1 was chosen, so we don't have problems with cofactors (for secp256k1, cofactor is 1). 
A check that a group element belongs to the group happens during compressed point deserialization.
