### ISSUE TITLE
Test complex signatures (de)serialization 

### ISSUE THREAD

**Issue by kushti** [ScorexFoundation/sigmastate-interpreter#169]
Currently, ComplexSigSpecification checks interactive communication between a prover and a verifier. It is also  worth to check serialization and deserialization of complex signatures.

**Comment by kushti** [comment]
@greenhat actually, it seems (de)serialization is already checked with current verifier logic, but let's add some  complex signature examples

**Comment by greenhat** [comment]
@kushti I'm going through tests in `ComplexSigSpecification` trying to come up with more complex sig examples. If you have any ideas/cases, please let me know.

**Comment by kushti** [comment]
Made also nested thresholds test
