### ISSUE TITLE
Add an array of Digest32 values in ErgoLikeTransaction

### ISSUE THREAD

**Issue by ergomorphic** [ScorexFoundation/sigmastate-interpreter#196]
With an introduction of `additionalTokens` it make sense now to to have an array of Digest32 values in transaction, which is serialized together with transaction.

`val digests: Array[Digest32] // all digests used in this transaction`

This array should be used as a vacabulary for serialization and deserialization of boxes.
Instead of serializing the same tokenId as Digest32, we can instead serialize an index in `digests` array.

This is good not only for great savings in a serialization space, but it will also reduce memory footprint, alloc/garbage size, and also improve equals performance because of reference equality fast path.

We also can consider using `digests` array not only for tokenId, but for all other digests in a transaction.

**Comment by kushti** [comment]
sounds reasonable

**Comment by greenhat** [comment]
Fixed in #229
