### ISSUE TITLE
Implement (de)serialization for the remaining nodes

### ISSUE THREAD

**Issue by greenhat** [ScorexFoundation/sigmastate-interpreter#206]
Added in #250 :
- `ValUse` (done in #266)
- `BlockValue` (done in #266)
- `FuncValue` (done in #266)

**Comment by catena2w** [comment]
@greenhat is it already done? What PR does close this issue?

**Comment by greenhat** [comment]
@catena2w It's done in https://github.com/ScorexFoundation/sigmastate-interpreter/pull/250 
As soon as #250 is merged it will be closed.
