### ISSUE TITLE
Unify ErgoLikeTransaction.id between Ergo, Scorex and Sigma

### ISSUE THREAD

**Issue by ergomorphic** [ScorexFoundation/sigmastate-interpreter#216]
Related to #205 and Scorex [PR 294](https://github.com/ScorexFoundation/Scorex/pull/294)

Scorex `Transaction.id` is of type `ModifierId` which is tagged `String`.
Sigma `ErgoLikeTransaction.id` is of type `Array[Byte]`.

This prevents mixing of this two traits.

Todo:
- [x] backport to `hotfix/v0.9.5` branch;
- [x] publish v0.9.5;

**Comment by greenhat** [comment]
used in ergo in 
https://github.com/ergoplatform/ergo/pull/422/files
