### ISSUE TITLE
Make ErgoScript syntax subset of Scala

### ISSUE THREAD

**Issue by ergomorphic** [ScorexFoundation/sigmastate-interpreter#227]
To make ErgoScript cut-and-paste compatible with future SigmaDsl for Scala.
 - [ ] Change 'let' keyword to 'val' keyword
 - [ ] replace `fun (x: T) = {...}` with `(x: T) => {...}` or `{ (x: T) => ... }` or `{ x: T => ... }` 
 - [x] Option[T].value => Option[T].get

These are the only syntactic differences, everything else is exactly the same.

**Comment by greenhat** [comment]
Sounds good. I like the `{ x: T => ... }`.

**Comment by ergomorphic** [comment]
@greenhat Me too, but it doesn't scale to multiple args, so `{ (x: T, y: U) => ... }` is more universal
