### ISSUE TITLE
Create tests for lazy evaluation of `OR`, `AND` in addition to existing tests

### ISSUE THREAD

**Issue by greenhat** [ScorexFoundation/sigmastate-interpreter#247]
I suppose we should short circuit on first `true` element and do not evaluate the rest of the elements.
Here is the code example that now is failing and should work:
`true || (1/0 == 1)` 

Reported in #246

**Comment by ergomorphic** [comment]
This should work after #250 is merged. Corresponding test can be added as part of #250 .
