### ISSUE TITLE
Explore gzip'ing of serialized scripts

### ISSUE THREAD

**Issue by greenhat** [ScorexFoundation/sigmastate-interpreter#263]
PR #262 

I've instrumented the `Interpreter.verify` call to measure the "compressibility" of the serialized expression. Then I ran our tests.
Among all tests: 

Total samples: 326, winning: 22.39%; winning after 52 bytes size(153 samples): 47.71%, 

where "winning" means compressed size was smaller than original. 52 bytes size is the threshold after which compression has "wins".

Excluded tests ("spammers"):
- CoinEmmisionSpec;
- BlockchainSimulationSpec;
- ThresholdSpec.property("threshold proving of different trees");
- Rule110Spec.property("rule110 - one bit per output (old version)");

Here are separate runs for our example scripts:
- AtomicSwapExampleSpecification - compression loses 100%;
- AssetsAtomicExchangeSpecification - compression wins 100%;
- CrowdfundingExampleSpecification - compression wins 100%;
- FsmExampleSpecification - compression wins 100%;
- MASTExampleSpecification - compression loses 100%;
- DemurrageExampleSpecification - compression loses 100%;
- OracleExamplesSpecification - Total samples: 3, winning: 33.33%; winning after 292 bytes size(1 samples): 100.00%
- Rule110Specification - compression wins 100%;

We could introduce the header for the serialized script with an attribute specifying that compression was used. When serializing the script we can check if compression makes sense and only then apply it.

**Comment by ergomorphic** [comment]
@greenhat could please change an instrumentation to output CSV text file with the following columns: 
ExampleName, SourceCode, OriginalSerializedSize, CompressedSize, Orig/Comp Ration
This can further analized in Excel

**Comment by greenhat** [comment]
@ergomorphic Done.
[GZipMeasurements.csv.zip](https://github.com/ScorexFoundation/sigmastate-interpreter/files/2460529/GZipMeasurements.csv.zip)

Also disabled the whole BlockchainSimulationSpec and old test in Rule110Spec for being "spammy".

**Comment by kushti** [comment]
We also need to consider that GZip is adding complexity in specification and alternative clients
