### ISSUE TITLE
Check script tree depth limit during deserialization

### ISSUE THREAD

**Issue by ergomorphic** [ScorexFoundation/sigmastate-interpreter#270]
- This issue defines behavior of script interpreter when given enormously deep tree during transaction validation
-  Script trees with at least `MaxTreeDepth` levels should be supported
- When transaction is validated the script is deserialized for execution.
- The script should be checked by deserializer for it's depth using `level` field in the deserializer.
- The scripts with more than `MaxTreeDepth` levels are considered malicious which should lead to deserializer throwing the corresponding exception.
- every recursive serializer should check `MaxTreeDepth` (ValueSerializer, DataSerializer, SigmaBoolean.serializer)

**Comment by aslesarenko** [comment]
Closed by #482
