### ISSUE TITLE
Add new field Box.creationInfo

### ISSUE THREAD

**Issue by ergomorphic** [ScorexFoundation/sigmastate-interpreter#276]
After #254 is merged, the new obligatory register will be available. 
Access to this script can be simplified by adding a new Box field.
This will reduce code for example `SELF.R3[(Long, Array[Byte])].get._1` to `SELF.creationInfo._1`

**Comment by ergomorphic** [comment]
@kushti please confirm

**Comment by kushti** [comment]
@ergomorphic I confirm!
