### ISSUE TITLE
List of constraints on ErgoTree to simplify cost function

### ISSUE THREAD

**Issue by ergomorphic** [ScorexFoundation/sigmastate-interpreter#285]
* All the inputs to a script (registers and context extensions) should be of limited size
* BigInteger is about 256 bits (mb better to call the type BigInt256 then)
* Combinators (map, fold, etc) should be limited. In the simplest case they scan produce scalar values only. In more extreme case, we could require a combinator function can produce value of no bigger cost than of input element.

**Comment by aslesarenko** [comment]
Implemented in v2.2
