### ISSUE TITLE
Make atLeast to operate on SigmaProp values

### ISSUE THREAD

**Issue by ergomorphic** [ScorexFoundation/sigmastate-interpreter#294]
Currently atLeast is defined as function `atLeast: Array[Boolean] => Boolean`.
However it operates on values of type SigmaProp.
Thus its type should be changed to `atLeast: Array[SigmaProp] => SigmaProp
ThresholdSpecification should be fixed accordingly.

**Comment by greenhat** [comment]
Done in #317
