### ISSUE TITLE
Add supported operation flags to AVLTree type

### ISSUE THREAD

**Issue by kushti** [ScorexFoundation/sigmastate-interpreter#297]
Currently, all the operations (insert, remove, update) are supported for AVL+ Tree in scripts. We can add (a single byte containing) flags to the tree constructor indicating whether particular operations are supported or not. Thus we can have read-only trees, append-only trees, remove-only trees, and such options potentially give us a broader range of protocols. It would be reasonable to consider operations to (dis) allow operations (so to create a new tree with disabled or enabled operations of a certain kind),  

Another topic to investigate is how to convert some entities (e.g. keys) into operations on a tree (by implementing examples).

**Comment by aslesarenko** [comment]
Implemented in v2.0
