### ISSUE TITLE
Switch the tests to the new compiler pipeline (with coster)

### ISSUE THREAD

**Issue by greenhat** [ScorexFoundation/sigmastate-interpreter#314]

**Comment by ergomorphic** [comment]
@greenhat We need to remove `SigmaSpecializer.specialize` from `compileWithCosting` because: 
1) it is no longer needed (the rules in RuntimeCosting can handle all the cases) 
2) It unfolds Val definitions of Block thus blowing up the code which is given to RuntimeCosting on the next step

**Comment by greenhat** [comment]
@ergomorphic Does it mean that we should remove `SigmaSpecializer` from our compiler pipeline (`SigmaCompiler.compile`)? Is it safe to delete `SigmaSpecializer` completely?

**Comment by ergomorphic** [comment]
@greenhat yes, I suggest to remove specialize() from compileWithCosting. So we can gradually switch to a new pipeline. Otherwise many tests fail.

**Comment by greenhat** [comment]
Done in #317
