### ISSUE TITLE
Make SMethod a single point of declaration

### ISSUE THREAD

**Issue by ergomorphic** [ScorexFoundation/sigmastate-interpreter#344]
For methods we need to improve infrastructure. 
We need to extends SMethod, so that it can be a single point of method declaration. 
And all other code should just use info from SMethod. 
This include Parser/Typer/Coster/TreeBuilder.

The goal:
To add a new method we just need to register new SMethod for the corresponding type.

**Comment by aslesarenko** [comment]
The basic infranstructure is finished so this general issue can be closed. For more specific tasks new issues can be created.
