### ISSUE TITLE
Add CONTEXT global variable

### ISSUE THREAD

**Issue by ergomorphic** [ScorexFoundation/sigmastate-interpreter#350]
### CONTEXT variable

It has type `Context` (Internal type SContext).
It should evaluate to current context so that we can declare global library functions.
```scala
def selfHasTokens(ctx: Context): Boolean = {
  ctx.SELF.tokens.length > 0
}
```
that can later be used
```scala
selfHasTokens(CONTEXT) && HEIGHT > 100
```
Note that existing HEIGHT variable should remain as a shortcut to `CONTEXT.HEIGHT`.

**Comment by greenhat** [comment]
@ergomorphic Following our discussion in https://github.com/ScorexFoundation/sigmastate-interpreter/pull/358#pullrequestreview-194110600. Could you please clarify how do you see the compilation and evaluation of `CONTEXT` global variable. I cannot think of anything other than what I did in the aforementioned PR (IR node based on `NotReadyValue[SContext]`). Binder should convert it into something. What should it be?
