### ISSUE TITLE
A contract is causing an unexpected exception during deserialization 

### ISSUE THREAD

**Issue by kushti** [ScorexFoundation/sigmastate-interpreter#374]
The following contract https://gist.github.com/kushti/1e9f6d0add6a5fd926743aaa26d448bd is causing the following exception https://gist.github.com/kushti/6e5afdb21a5c4d20bc49bca8b9eaf23f on line 102.

**Comment by greenhat** [comment]
Fixed in #375. Confirmed green on current `master`.
