### ISSUE TITLE
Create serializer and corresponding tests for Transformer instantiations

### ISSUE THREAD

**Issue by kushti** [ScorexFoundation/sigmastate-interpreter#40]
We need for serializers for many more classes, including Transformer descendants family (MapCollection, ForAll, Exists etc). Tests (similar to which are already exist in "sigmastate.serialization" package) are also needed

**Comment by Dmdv** [comment]
#49 partially implemented and can be review

**Comment by catena2w** [comment]
fixed in https://github.com/ScorexFoundation/sigmastate-interpreter/pull/104
