### ISSUE TITLE
Finish costing for trees 

### ISSUE THREAD

**Issue by kushti** [ScorexFoundation/sigmastate-interpreter#413]
A script which is calling .digest on a tree is causing the following error:

Invalid primitive in Cost function: MethodCall(s989, scalan.Base$Exp special.sigma.SigmaDsl$AvlTree.digest(), [], true)
scalan.Base$StagingException: Invalid primitive in Cost function: MethodCall(s989, scalan.Base$Exp special.sigma.SigmaDsl$AvlTree.digest(), [], true)

**Comment by aslesarenko** [comment]
@kushti How to reproduce?

**Comment by kushti** [comment]
@aslesarenko see "simple ico example - fixing stage" test

**Comment by aslesarenko** [comment]
fixed in #429
