### ISSUE TITLE
Error in ErgoDSL when accessing tokens

### ISSUE THREAD

**Issue by scalahub** [ScorexFoundation/sigmastate-interpreter#414]
The code `val inToken = INPUTS(0).tokens(0)._1 == tokenId` gives below error:

`Don't know how to evalNode(MethodCall(ByIndex(Inputs,IntConstant(0),None),SMethod(SBox,tokens,Coll[(Coll[SByte],SLong)],8,Some(<function1>)),Vector()))`

Complete code in file [`OracleTokenExamplesSpecification.scala`](https://github.com/ScorexFoundation/sigmastate-interpreter/blob/protocol_examples_v2.0/src/test/scala/sigmastate/utxo/examples/OracleTokenExamplesSpecification.scala) in branch [`protocol_examples_v2.0`](https://github.com/ScorexFoundation/sigmastate-interpreter/tree/protocol_examples_v2.0)

https://github.com/ScorexFoundation/sigmastate-interpreter/blob/e40bdf73d9b2d1ae91f1b2e5d7b80f2cda3c608b/src/test/scala/sigmastate/utxo/examples/OracleTokenExamplesSpecification.scala#L124

**Comment by greenhat** [comment]
I cannot reproduce it. It works.
