### ISSUE TITLE
Implement modular arithmetic operations

### ISSUE THREAD

**Issue by kushti** [ScorexFoundation/sigmastate-interpreter#415]
The following test is failing, though #324 is done:

// TODO: enable after https://github.com/ScorexFoundation/sigmastate-interpreter/issues/324 is done
  property("modular arithmetic ops") {

it's failing with:

Don't know how to evalNode(ModQ(Select(IntConstant(10),toBigInt,Some(SBigInt))))
sigmastate.lang.exceptions.CosterException: Don't know how to evalNode(ModQ(Select(IntConstant(10),toBigInt,Some(SBigInt))))

**Comment by greenhat** [comment]
Fixed in #488

**Comment by greenhat** [comment]
Closed in favor of #327
