### ISSUE TITLE
Finish implementation of zipWith

### ISSUE THREAD

**Issue by kushti** [ScorexFoundation/sigmastate-interpreter#419]
It seems that .zipWith is implemented in parser but no further:

see e.g. "prover enriching context - xor" example:

def Xor(c1: Coll[Byte], c2: Coll[Byte]): Coll[Byte] = c1.zipWith(c2, { (x, y) => x ^ y })
                                                                ^
Cannot find method 'zipWith' in in the object Ident(c1,NoType) of Product type with methods List(SMethod(sigmastate.SCollection$@41bf79da,size,(Coll[IV]) => SInt,1,None), SMethod(sigmastate.SCollection$@41bf79da,getOrElse,[IV](Coll[IV],SInt,IV) => IV,2,Some(<function1>)), SMethod(sigmastate.SCollection$@41bf79da,map,[IV,OV](Coll[IV],(IV) => OV) => Coll[OV],3,None), SMethod(sigmastate.SCollection$@41bf79da,exists,[IV](Coll[IV],(IV) => SBoolean) => SBoolean,4,None), SMethod(sigmastate.SCollection$@41bf79da,fold,[IV,OV](Coll[IV],OV,(OV,IV) => OV) => OV,5,None), SMethod(sigmastate.SCollection$@41bf79da,forall,[IV](Coll[IV],(IV) => SBoolean) => SBoolean,6,None), SMethod(sigmastate.SCollection$@41bf79da,slice,[IV](Coll[IV],SInt,SInt) => Coll[IV],7,None), SMethod(sigmastate.SCollection$@41bf79da,filter,[IV](Coll[IV],(IV) => SBoolean) => Coll[IV],8,None), SMethod(sigmastate.SCollection$@41bf79da,append,[IV](Coll[IV],Coll[IV]) => Coll[IV],9,None), SMethod(sigmastate.SCollection$@41bf79da,apply,[IV](Coll[IV],SInt) => IV,10,None), SMethod(sigmastate.SCollection$@41bf79da,<<,[IV](Coll[IV],SInt) => Coll[IV],11,None), SMethod(sigmastate.SCollection$@41bf79da,>>,[IV](Coll[IV],SInt) => Coll[IV],12,None), SMethod(sigmastate.SCollection$@41bf79da,>>>,(Coll[SBoolean],SInt) => Coll[SBoolean],13,None), SMethod(sigmastate.SCollection$@41bf79da,indices,(Coll[IV]) => Coll[SInt],14,Some(<function1>)), SMethod(sigmastate.SCollection$@41bf79da,flatMap,[IV,OV](Coll[IV],(IV) => Coll[OV]) => Coll[OV],15,Some(<function1>)), SMethod(sigmastate.SCollection$@41bf79da,segmentLength,[IV](Coll[IV],(IV) => SBoolean,SInt) => SInt,16,Some(<function1>)), SMethod(sigmastate.SCollection$@41bf79da,indexWhere,[IV](Coll[IV],(IV) => SBoolean,SInt) => SInt,17,Some(<function1>)), SMethod(sigmastate.SCollection$@41bf79da,lastIndexWhere,[IV](Coll[IV],(IV) => SBoolean,SInt) => SInt,18,Some(<function1>)), SMethod(sigmastate.SCollection$@41bf79da,patch,[IV](Coll[IV],SInt,Coll[IV],SInt) => Coll[IV],19,Some(<function1>)), SMethod(sigmastate.SCollection$@41bf79da,updated,[IV](Coll[IV],SInt,IV) => Coll[IV],20,Some(<function1>)), SMethod(sigmastate.SCollection$@41bf79da,updateMany,[IV](Coll[IV],Coll[SInt],Coll[IV]) => Coll[IV],21,Some(<function1>)), SMethod(sigmastate.SCollection$@41bf79da,unionSets,[IV](Coll[IV],Coll[IV]) => Coll[IV],22,Some(<function1>)), SMethod(sigmastate.SCollection$@41bf79da,diff,[IV](Coll[IV],Coll[IV]) => Coll[IV],23,Some(<function1>)), SMethod(sigmastate.SCollection$@41bf79da,intersect,[IV](Coll[IV],Coll[IV]) => Coll[IV],24,Some(<function1>)), SMethod(sigmastate.SCollection$@41bf79da,prefixLength,[IV](Coll[IV],(IV) => SBoolean) => SInt,25,Some(<function1>)), SMethod(sigmastate.SCollection$@41bf79da,indexOf,[IV](Coll[IV],IV,SInt) => SInt,26,Some(<function1>)), SMethod(sigmastate.SCollection$@41bf79da,lastIndexOf,[IV](Coll[IV],IV,SInt) => SInt,27,Some(<function1>)), SMethod(sigmastate.SCollection$@41bf79da,find,[IV](Coll[IV],(IV) => SBoolean) => Option[IV],28,Some(<function1>)), SMethod(sigmastate.SCollection$@41bf79da,zip,[IV,OV](Coll[IV],Coll[OV]) => Coll[(IV,OV)],29,Some(<function1>)), SMethod(sigmastate.SCollection$@41bf79da,distinct,[IV](Coll[IV]) => Coll[IV],30,Some(<function1>)), SMethod(sigmastate.SCollection$@41bf79da,startsWith,[IV](Coll[IV],Coll[IV],SInt) => SBoolean,31,Some(<function1>)), SMethod(sigmastate.SCollection$@41bf79da,endsWith,[IV](Coll[IV],Coll[IV]) => SBoolean,32,Some(<function1>)), SMethod(sigmastate.SCollection$@41bf79da,partition,[IV](Coll[IV],(IV) => SBoolean) => (Coll[IV],Coll[IV]),33,Some(<function1>)), SMethod(sigmastate.SCollection$@41bf79da,mapReduce,[IV,K,V](Coll[IV],(IV) => (K,V),((V,V)) => V) => Coll[(K,V)],34,Some(<function1>)))
sigmastate.lang.exceptions.MethodNotFound: 
line 3:   def Xor(c1: Coll[Byte], c2: Coll[Byte]): Coll[Byte] = c1.zipWith(c2, { (x, y) => x ^ y })

**Comment by greenhat** [comment]
We don't have `Coll.zipWith` implementation anywhere in the pipeline. There is a lonely parser test to check if it's parsed as `Apply` term. Nor do we have `zipWith` planned in https://github.com/ScorexFoundation/sigmastate-interpreter/blob/0bc2c2b1bf2a8f05b38df2f62ac1fa282ee84387/docs/LangSpec.md#L465

**Comment by kushti** [comment]
This method will not be implemented (at least for now), see https://github.com/ScorexFoundation/sigmastate-interpreter/issues/1004 for reasoning
