### ISSUE TITLE
Finish costing for .indices

### ISSUE THREAD

**Issue by kushti** [ScorexFoundation/sigmastate-interpreter#421]
Currently ignored test "indices" throws:

Invalid primitive in Cost function: MethodCall(s364, scalan.Base$Exp special.collection.Colls$Coll.indices(), [], true)
scalan.Base$StagingException: Invalid primitive in Cost function: MethodCall(s364, scalan.Base$Exp special.collection.Colls$Coll.indices(), [], true)

**Comment by greenhat** [comment]
Fixed
