### ISSUE TITLE
Expression t._1(t._2) cannot be costed because t is lambda argument

### ISSUE THREAD

**Issue by kushti** [ScorexFoundation/sigmastate-interpreter#427]
Currently ignored test "Func context variable" has comment a "costing: expression t._1(t._2) cannot be costed because t is lambda argument".

We should decide, whether to improve a costing procedure to make the example test passing, or abandon it totally.

**Comment by aslesarenko** [comment]
Closing this as it no longer actual. And the corresponding test is removed in https://github.com/ScorexFoundation/sigmastate-interpreter/pull/868
