### ISSUE TITLE
Soft-forkability

### ISSUE THREAD

**Issue by aslesarenko** [ScorexFoundation/sigmastate-interpreter#437]
This is aggregate issue.
Before closing it the following issues should be closed: #438 

This is to allow soft-forkability of Sigma contract validation.

Soft-forkability for validation is defined as the following:
1. The validation result is extended from simple True|False to be a pair 
(isFork: Boolean, isValid: Boolean)
1. If during contract validation an old version of the code recognizes *valid*, but *new* construction in Sigma byte code, then:
    - if the validation is performed for existing block created elsewhere then contract validation finishes with (isFork = true, isValid = True) result
    - if the validation is performed before adding the transaction to the new block candidate
then the result is (isFork = true, isValid = False)
1. Otherwize, if no new construct are detected the contract is executed normally and the result is (isFork = false, isValid = evaluationResult)

isFork result parameter can be used by the upper level of protocol to make decisions about status of the transaction.

**Comment by catena2w** [comment]
Should be coordinated with https://github.com/ergoplatform/ergo/issues/581
