### ISSUE TITLE
Compress OpCode ranges to simplify soft-forkability

### ISSUE THREAD

**Issue by aslesarenko** [ScorexFoundation/sigmastate-interpreter#438]
Currently the range of OpCodes is not dense. There are windows of 1, 2, 5, etc reserved opcodes.
They should be compressed and all the reserved opcodes should be at the end of the byte range.
Also, a separate constant MaxOpCode should be added to mark the last valid opCode in the current release.
When a new operation code is added in a new release the constant should be increased.

This will allow to add new operations and easily check for soft-forkability condition during de-serialization of new scripts by old versions. 
`if (desrializedOpCode > MaxOpCode) soft-fork else normal-operation`

**Comment by catena2w** [comment]
As far as I understood, that will break binary compatibility.
We've promised not to break it if no security issues will be found.
