### ISSUE TITLE
Add checks of acceptable register and context variables

### ISSUE THREAD

**Issue by aslesarenko** [ScorexFoundation/sigmastate-interpreter#447]
Before constant can be added as context variable (getVar) or register (getReg) it should be checked for allowed type and values range.

This issue is to implement all this checks in a single function, and use this function wherever it is necessary.

**Comment by gostkin** [comment]
Using map of EvaluatedType guarantees type correctness & values range, Box size is bordered above, so we're secured from spam attacks. Transaction context extension size is bordered above by block size, so it was discussed that there's no problem.
