### ISSUE TITLE
Split consensus-critical and not critical parts of the code.

### ISSUE THREAD

**Issue by kushti** [ScorexFoundation/sigmastate-interpreter#449]
Consesus-critical code (abstract syntax tree, its (de)serialization rules and binary formats, costing rules, tree reduction rules) should be in a separate module, and possibly marked somehow (e.g. via annotations),

**Comment by aslesarenko** [comment]
@kushti All the code in 'sigmastate.lang` package belong to frontend and can be moved to a separate downstream module (let's call it `frontend`). 
Everything else is used in consensus, maybe some of it can be also moved to downstream module.
What will remain can be moved to `core` module.
