### ISSUE TITLE
"(De)Serialization roundtrip failed"

### ISSUE THREAD

**Issue by kushti** [ScorexFoundation/sigmastate-interpreter#451]
See "simple ico example - withdrawal stage" in ico-example branch: 

(De)Serialization roundtrip failed for the tree: BlockValue(Vector(ValDef(1,List(),ExtractRegisterAs(Self,R5,Option[SAvlTree]).get), ValDef(2,List(),Slice(Outputs,IntConstant(1),Minus(SizeOf(Outputs), IntConstant(1)))), ValDef(3,List(),MapCollection(ValUse(2,Coll[SBox]),FuncValue(WrappedArray((3,SBox)),ExtractScriptBytes(ValUse(3,SBox)))))),BinAnd(EQ(MethodCall(ValUse(1,SAvlTree),SMethod(SAvlTree,remove,(SAvlTree,Coll[Coll[SByte]],Coll[SByte]) => Option[SAvlTree],14,Some(<function1>)),Vector(ValUse(3,Coll[Coll[SByte]]), GetVar(1,Option[Coll[SByte]]).get),Map()).get,ExtractRegisterAs(ByIndex(Outputs,IntConstant(0),None),R5,Option[SAvlTree]).get),ForAll(MethodCall(MapCollection(MethodCall(ValUse(1,SAvlTree),SMethod(SAvlTree,getMany,(SAvlTree,Coll[Coll[SByte]],Coll[SByte]) => Coll[Option[Coll[SByte]]],11,Some(<function1>)),Vector(ValUse(3,Coll[Coll[SByte]]), GetVar(2,Option[Coll[SByte]]).get),Map()),FuncValue(WrappedArray((4,Option[Coll[SByte]])),ValUse(4,Option[Coll[SByte]]).get)),SMethod(sigmastate.SCollection$@43a51d00,zip,(Coll[Coll[SByte]],Coll[Coll[SByte]]) => Coll[(Coll[SByte],Coll[SByte])],29,Some(<function1>)),Vector(MapCollection(ValUse(2,Coll[SBox]),FuncValue(WrappedArray((4,SBox)),LongToByteArray(ExtractAmount(ValUse(4,SBox)))))),Map()),FuncValue(WrappedArray((4,(Coll[SByte],Coll[SByte]))),EQ(SelectField(ValUse(4,(Coll[SByte],Coll[SByte])),1),SelectField(ValUse(4,(Coll[SByte],Coll[SByte])),2)))))) did not equal BlockValue(Vector(ValDef(1,List(),ExtractRegisterAs(Self,R5,Option[SAvlTree]).get), ValDef(2,List(),Slice(Outputs,IntConstant(1),Minus(SizeOf(Outputs), IntConstant(1)))), ValDef(3,List(),MapCollection(ValUse(2,Coll[SBox]),FuncValue(Vector((3,SBox)),ExtractScriptBytes(ValUse(3,SBox)))))),BinAnd(EQ(MethodCall(ValUse(1,SAvlTree),SMethod(SAvlTree,remove,(SAvlTree,Coll[Coll[SByte]],Coll[SByte]) => Option[SAvlTree],14,Some(<function1>)),Vector(ValUse(3,Coll[Coll[SByte]]), GetVar(1,Option[Coll[SByte]]).get),Map()).get,ExtractRegisterAs(ByIndex(Outputs,IntConstant(0),None),R5,Option[SAvlTree]).get),ForAll(MethodCall(MapCollection(MethodCall(ValUse(1,SAvlTree),SMethod(SAvlTree,getMany,(SAvlTree,Coll[Coll[SByte]],Coll[SByte]) => Coll[Option[Coll[SByte]]],11,Some(<function1>)),Vector(ValUse(3,Coll[Coll[SByte]]), GetVar(2,Option[Coll[SByte]]).get),Map()),FuncValue(Vector((4,Option[Coll[SByte]])),ValUse(4,Option[Coll[SByte]]).get)),SMethod(sigmastate.SCollection$@43a51d00,zip,[OV](Coll[Coll[SByte]],Coll[OV]) => Coll[(Coll[SByte],OV)],29,Some(<function1>)),Vector(MapCollection(ValUse(2,Coll[SBox]),FuncValue(Vector((4,SBox)),LongToByteArray(ExtractAmount(ValUse(4,SBox)))))),Map()),FuncValue(Vector((4,(Coll[SByte],Coll[SByte]))),EQ(SelectField(ValUse(4,(Coll[SByte],Coll[SByte])),1),SelectField(ValUse(4,(Coll[SByte],Coll[SByte])),2))))))
ScalaTestFailureLocation: sigmastate.helpers.SigmaTestingCommons at (SigmaTestingCommons.scala:50)
Expected :BlockValue(Vector(ValDef(1,List(),ExtractRegisterAs(Self,R5,Option[SAvlTree]).get), ValDef(2,List(),Slice(Outputs,IntConstant(1),Minus(SizeOf(Outputs), IntConstant(1)))), ValDef(3,List(),MapCollection(ValUse(2,Coll[SBox]),FuncValue(Vector((3,SBox)),ExtractScriptBytes(ValUse(3,SBox)))))),BinAnd(EQ(MethodCall(ValUse(1,SAvlTree),SMethod(SAvlTree,remove,(SAvlTree,Coll[Coll[SByte]],Coll[SByte]) => Option[SAvlTree],14,Some(<function1>)),Vector(ValUse(3,Coll[Coll[SByte]]), GetVar(1,Option[Coll[SByte]]).get),Map()).get,ExtractRegisterAs(ByIndex(Outputs,IntConstant(0),None),R5,Option[SAvlTree]).get),ForAll(MethodCall(MapCollection(MethodCall(ValUse(1,SAvlTree),SMethod(SAvlTree,getMany,(SAvlTree,Coll[Coll[SByte]],Coll[SByte]) => Coll[Option[Coll[SByte]]],11,Some(<function1>)),Vector(ValUse(3,Coll[Coll[SByte]]), GetVar(2,Option[Coll[SByte]]).get),Map()),FuncValue(Vector((4,Option[Coll[SByte]])),ValUse(4,Option[Coll[SByte]]).get)),SMethod(sigmastate.SCollection$@43a51d00,zip,[OV](Coll[Coll[SByte]],Coll[OV]) => Coll[(Coll[SByte],OV)],29,Some(<function1>)),Vector(MapCollection(ValUse(2,Coll[SBox]),FuncValue(Vector((4,SBox)),LongToByteArray(ExtractAmount(ValUse(4,SBox)))))),Map()),FuncValue(Vector((4,(Coll[SByte],Coll[SByte]))),EQ(SelectField(ValUse(4,(Coll[SByte],Coll[SByte])),1),SelectField(ValUse(4,(Coll[SByte],Coll[SByte])),2))))))
Actual   :(De)Serialization roundtrip failed for the tree: BlockValue(Vector(ValDef(1,List(),ExtractRegisterAs(Self,R5,Option[SAvlTree]).get), ValDef(2,List(),Slice(Outputs,IntConstant(1),Minus(SizeOf(Outputs), IntConstant(1)))), ValDef(3,List(),MapCollection(ValUse(2,Coll[SBox]),FuncValue(WrappedArray((3,SBox)),ExtractScriptBytes(ValUse(3,SBox)))))),BinAnd(EQ(MethodCall(ValUse(1,SAvlTree),SMethod(SAvlTree,remove,(SAvlTree,Coll[Coll[SByte]],Coll[SByte]) => Option[SAvlTree],14,Some(<function1>)),Vector(ValUse(3,Coll[Coll[SByte]]), GetVar(1,Option[Coll[SByte]]).get),Map()).get,ExtractRegisterAs(ByIndex(Outputs,IntConstant(0),None),R5,Option[SAvlTree]).get),ForAll(MethodCall(MapCollection(MethodCall(ValUse(1,SAvlTree),SMethod(SAvlTree,getMany,(SAvlTree,Coll[Coll[SByte]],Coll[SByte]) => Coll[Option[Coll[SByte]]],11,Some(<function1>)),Vector(ValUse(3,Coll[Coll[SByte]]), GetVar(2,Option[Coll[SByte]]).get),Map()),FuncValue(WrappedArray((4,Option[Coll[SByte]])),ValUse(4,Option[Coll[SByte]]).get)),SMethod(sigmastate.SCollection$@43a51d00,zip,(Coll[Coll[SByte]],Coll[Coll[SByte]]) => Coll[(Coll[SByte],Coll[SByte])],29,Some(<function1>)),Vector(MapCollection(ValUse(2,Coll[SBox]),FuncValue(WrappedArray((4,SBox)),LongToByteArray(ExtractAmount(ValUse(4,SBox)))))),Map()),FuncValue(WrappedArray((4,(Coll[SByte],Coll[SByte]))),EQ(SelectField(ValUse(4,(Coll[SByte],Coll[SByte])),1),SelectField(ValUse(4,(Coll[SByte],Coll[SByte])),2))))))

**Comment by greenhat** [comment]
Cannot reproduce, the test is green both locally and on CI (see https://github.com/ScorexFoundation/sigmastate-interpreter/pull/450 )
