### ISSUE TITLE
Unexpected Costing Procedure Behavior  

### ISSUE THREAD

**Issue by kushti** [ScorexFoundation/sigmastate-interpreter#452]
It is expected that with growing input cost is also growing. However, this is not the case for current costing procedure. Take a look to "simple ico example - fundraising stage only" in the ico-example branch. Depending on "funderBoxCount" parameter value, costs are as follows:
2 | 4248
20 | "Estimated expression complexity 1711276242 exceeds the limit 1000000"
200 | 3800 
2000 | 32600
20000 | 325800

**Comment by gostkin** [comment]
#505  shows that now everything is fine
