### ISSUE TITLE
Type check on deserialization

### ISSUE THREAD

**Issue by catena2w** [ScorexFoundation/sigmastate-interpreter#454]
Add type checking when deserializing script from bytes

**Comment by greenhat** [comment]
@aslesarenko @catena2w Current status of script deserialization methods:
- `DeserializeRegister` is implemented with type checking (covered with the test);
- `DeserializeContext` is implemented without type checking;
- `ExecuteFromVar`, `ExecuteFromReg` are not implemented;
I'm adding type checking to `DeserializeContext`. 
Let me know if the scope of this issue should include implementing the `ExecuteFrom*` functions.

**Comment by catena2w** [comment]
I meant ErgoTreeSerializer and it's methods

**Comment by greenhat** [comment]
Resolved in #459
