### ISSUE TITLE
byIndex costing failed when index is computed

### ISSUE THREAD

**Issue by kushti** [ScorexFoundation/sigmastate-interpreter#456]
`val outsCount = OUTPUTS.size
  val lastIndex = outsCount - 1
  val feeOut = OUTPUTS(lastIndex)
`

is failing with "Invalid primitive in Cost function: -(s3689, s126)".

While 

`
val lastIndex = getVar[Int](3).get
val feeOut = OUTPUTS(lastIndex)
`

is okay, as well as `val outs = OUTPUTS.slice(1, outsCount - 1)`

**Comment by aslesarenko** [comment]
@kushti how to reproduce?

**Comment by kushti** [comment]
@aslesarenko please take a look at withdrawalScript in the IcoExample branch

**Comment by aslesarenko** [comment]
@kushti computed indexes are not supported. If some computed index is necessary, it can be passed as context argument of as register.

**Comment by aslesarenko** [comment]
Done in #534
