### ISSUE TITLE
Should sliced collection have properties of the original?

### ISSUE THREAD

**Issue by kushti** [ScorexFoundation/sigmastate-interpreter#463]
This is merely a question. 

When  we are doing:

INPUTS.slice(1, inputsCount).map({ (b: Box) =>
     val pk = b.R4[Coll[Byte]].get
     val value = longToByteArray(b.value)
     (pk, value)
  })

, all the inputs should have register R4 of the Coll[Byte] type, including INPUTS(0) (and INPUTS(inputsCount - 1).

Is this unavoidable and why?

**Comment by aslesarenko** [comment]
@kushti this is unavoidable. As in Scala if you access optional value via `get` then you get exception if the value is not present. However you can check b.R4[Coll[Byte]].isDefined using `if`, and have different branches for existing and absent registers.
