### ISSUE TITLE
Example which doesn't work in v4.x

### ISSUE THREAD

**Issue by kushti** [ScorexFoundation/sigmastate-interpreter#464]
UPD[@aslesarenko]:
Make sure the following example works with JITC.

For example,

path.fold(item, {(a: (Coll[Byte], Coll[Byte])) =>
    a._1.zip(a._2).map({ (c: (Byte, Byte)) => (c._1 ^ c._2).toByte })
})

does not compile, and I'm not sure whether it is okay or not. Please describe fold limitations in the spec.

**Comment by aslesarenko** [comment]
@kushti is this example is committed to some branch to reproduce?

**Comment by aslesarenko** [comment]
Nested loops are not supported in in AOT costing. 
Here `map` is nested in Fold and hence leads to error.
This example should work fine with JIT costing, moving to 4.0 milestone.

**Comment by aslesarenko** [comment]
bitwise xor operation `^` is not implemented in v4.x and in v5.0. 
So, exactly that example will not work in v5.0, but the following will work
```
val foo = path.fold(item, { (a: Coll[Byte], b: Coll[Byte]) =>
    a.zip(b).map({ (c: (Byte, Byte)) => (c._1 + c._2).toByte })
  })
```
See `property("nested loops: map inside fold")`

**Comment by aslesarenko** [comment]
Implementing ^ is part of #474 and will be done there. The test for this example is added, this issue can be closed.
