### ISSUE TITLE
Implement bitwise numeric OR, AND, XOR, inversion, bit shifts

### ISSUE THREAD

**Issue by greenhat** [ScorexFoundation/sigmastate-interpreter#474]
from #400 

- [ ] `~` (bitwise inversion);
- [ ] `|` (bitwise OR for Numeric);
- [ ] `&` (bitwise AND for Numeric);
- [ ] `^` (bitwise XOR for Numeric);
- [ ] `<<`, `>>`, `>>>` (bit shifts for Numeric);

**Comment by kushti** [comment]
duplicate of #1006
