### ISSUE TITLE
Getting error `key not found: s1763`

### ISSUE THREAD

**Issue by scalahub** [ScorexFoundation/sigmastate-interpreter#491]
The following file gives an error. 

https://github.com/ScorexFoundation/sigmastate-interpreter/blob/291bbbde39d33442a713e9651e419a8d89c8b29a/src/test/scala/sigmastate/utxo/examples/RevenueSharingExamplesSpecification.scala#L58

Error is given here:
https://gist.github.com/scalahub/a2f7277775bb28a923a8526e98ef4bfc

**Comment by aslesarenko** [comment]
Index expression of ByIndex() is not supported.
