### ISSUE TITLE
Soft-Forkability: table of allowed opcodes in cost function

### ISSUE THREAD

**Issue by aslesarenko** [ScorexFoundation/sigmastate-interpreter#499]
1) The validation rule `CheckCostFuncOperation` should be added 
2) it should be implemented similar to `CheckValidOpCode` rule.
3) is should be called from verifyCostFunc passing opCode of each graph node
4) New operation can be allowed in cost function by putting their op codes in block extension section (see `CheckValidOpCode`)

**Comment by greenhat** [comment]
Done in #503
