### ISSUE TITLE
NoSuchMethodException while verifying exp

### ISSUE THREAD

**Issue by scalahub** [ScorexFoundation/sigmastate-interpreter#546]
Getting following error 
```NoSuchMethodException: sigmastate.eval.CostingRules$GroupElementCoster.exp(scalan.Base$Exp```

while verifying script with `exp` instruction. Please see "faster costing" branch. File
MiscError.scala

https://github.com/ScorexFoundation/sigmastate-interpreter/blob/e4a6f4054edf5be1e54504b4f31a589244932082/src/test/scala/sigmastate/utxo/MiscErrors.scala#L210

**Comment by gostkin** [comment]
#548
