### ISSUE TITLE
SpamSpecification unification and coverage

### ISSUE THREAD

**Issue by aslesarenko** [ScorexFoundation/sigmastate-interpreter#563]
We need to do some unification among test cases. 
1) Each test case should have 
  - name, 
  - repeat parameters of scale 
  - script  generator which depend in scale 
  - list of functions which are covered.
  
2) Upon completion of SpamSpecification a report should be 
  generated and checked against saved report. 
  Set of covered operations should be checked and error 
  raised if any difference.

**Comment by greenhat** [comment]
Done.
