### ISSUE TITLE
DataJsonEncoder. Encode/Decode data to/from Json (similar to DataSerializer)

### ISSUE THREAD

**Issue by greenhat** [ScorexFoundation/sigmastate-interpreter#583]
Format:
`{ type: [type descriptor], value: [data] }`
where:
- `type descriptor` is an arbitrary type (e.g. `Coll[(Coll[Byte], Long)]`);
- `data` in human readable form.

Once you read the type, you know how to interpret the value. 
Examples:
```
{ type: "(Int, Int)"; value: { _1: 10; _2: 20 }}
{ type: "Coll[Byte]"; value: [1, 2, 3] }
{ type: "Coll[(Int, Int)]"; value: { _1: [1, 2, 3]; _2: [10, 20, 30] }}
{ type: "(Coll[(Int, Coll[Byte])], Long)"; 
  value: {
     _1: { _1: [1, 2, 3]; _2: [ [1, 1, 1], [2, 2], [3], [] ] } 
     _2: 100
  }
}
```

**Comment by aslesarenko** [comment]
UPDATE:
This is so called vectorized (or column based) representation of data
when collection of pairs is stored as pair of collections, and this rule is applied recursively over type structure.

It is not only the most compact, but it also corresponds to how Coll values are represented in SigmaDsl, so the parsing will also be very efficient.
