### ISSUE TITLE
Missing GroupElement.multiply costing

### ISSUE THREAD

**Issue by greenhat** [ScorexFoundation/sigmastate-interpreter#597]
UPD by @aslesarenko 
This depends on HF activation infrastructure of  #660 
The example below should fail in ErgoTree v0 and work in ErgoTree v1. 
There is nothing to fix, instead a new test should be added which fails under ET0 and passes under ET1

The following code `{ groupGenerator.multiply(groupGenerator) != groupGenerator }` when gone through the interpreter throws `Unexpected rejection cause: java.lang.NoSuchMethodException: sigmastate.eval.CostingRules$GroupElementCoster.multiply(scalan.Base$Ref), with root cause java.lang.NoSuchMethodException: sigmastate.eval.CostingRules$GroupElementCoster.multiply(scalan.Base$Ref)}` error.

**Comment by aslesarenko** [comment]
@greenhat How to reproduce? Which test?

**Comment by greenhat** [comment]
@aslesarenko There is a commented test in the spam test suite, plus the issue -
https://github.com/greenhat/sigma-spam/issues/19

**Comment by kushti** [comment]
@aslesarenko so how is it resolved ?

**Comment by aslesarenko** [comment]
Closed in #779
