### ISSUE TITLE
Fix CONTEXT.selfBoxIndex

### ISSUE THREAD

**Issue by greenhat** [ScorexFoundation/sigmastate-interpreter#603]
Now it always returns `-1`.
Caused by `eq` in http://github.com/ScorexFoundation/sigmastate-interpreter/blob/a598658d63ad822a99ef91ecc79da906ad779ffe/sigmastate/src/main/scala/sigmastate/eval/CostingDataContext.scala#L639-L639 
Switching to `==` fixes it.

To test add:
```
  property("CONTEXT.selfBoxIndex") {
    testEval("CONTEXT.selfBoxIndex == 0")
  }
```
to `TestingInterpreterSpecification.scala`.

**Comment by jasondavies** [comment]
Just ran into this bug.
