### ISSUE TITLE
Make sure this example works with JITC

### ISSUE THREAD

**Issue by greenhat** [ScorexFoundation/sigmastate-interpreter#604]
[UPD by @aslesarenko] A test case is needed for the script example below which make sure this script works with the new ErgoTreeEvaluator

A thorough check is needed.
Code:
```
 val headers = CONTEXT.headers
 val ids = headers.map({(h: Header) => h.id })
 val parentIds = headers.map({(h: Header) => h.parentId })
 headers.indices.slice(0, headers.size - 1).forall({ (i: Int) =>
   val parentId = parentIds(i)
   val id = ids(i + 1)
   parentId == id
 })
```
gives error:
```
scalan.Base$StagingException: Error in Evaluation.compile.evaluate(s4571 -> Placeholder(BaseElemLiftable<Int>)), with root cause scalan.Base$StagingException: Don't know how to evaluate(s4571 -> Placeholder(BaseElemLiftable<Int>))}
```

**Comment by aslesarenko** [comment]
@greenhat Is this test committed somewhere to reproduce?

**Comment by greenhat** [comment]
@aslesarenko No. The "Header.parentId consistency" spam test has a rewritten version of this test. I probably came up with the above code first and then mend to avoid hitting the exception.
