### ISSUE TITLE
Proving contract properties (formal verification)

### ISSUE THREAD

**Issue by greenhat** [ScorexFoundation/sigmastate-interpreter#609]
Document - https://github.com/ScorexFoundation/sigmastate-interpreter/pull/610

code - https://github.com/ScorexFoundation/sigmastate-interpreter/pull/617

# Plan:
## Generate ErgoTree from SigmaDsl. 
- [x] explore using macros for ErgoTree generation; 

## Crowdfunding Contract:
- [x] some properties of the Crowdfunding contract are already proven, see [source](http://github.com/ScorexFoundation/sigmastate-interpreter/blob/1f65d90cdab0388acc73bfa43797e39d3d9e32bc/contract-verification/src/main/scala/sigmastate/verification/contract/CrowdFundingContractVerification.scala#L34-L76)
- [ ] find and prove more properties.

### Rewrite ICO contracts:
- [ ] simplify/reduce the proof, the requirement is too complex [here](http://github.com/ScorexFoundation/sigmastate-interpreter/blob/1f65d90cdab0388acc73bfa43797e39d3d9e32bc/contract-verification/src/main/scala/sigmastate/verification/contract/ICOContractVerification.scala#L208-L208) 
- [ ] eliminate the use of `Option.getOrElse`;
### Prove ICO contract properties:
- [x] some properties of the ICO funding contract are already proven, see [source](http://github.com/ScorexFoundation/sigmastate-interpreter/blob/1f65d90cdab0388acc73bfa43797e39d3d9e32bc/contract-verification/src/main/scala/sigmastate/verification/contract/ICOContractVerification.scala#L197-L238)
- [ ] find and prove more properties for ICO funding contract.
- [ ] find and prove properties for ICO issuance contract.
- [ ] find and prove properties for ICO withdrawal contract.

**Comment by greenhat** [comment]
Having spent some time proving the contracts I'm seeing ErgoTree generation as the most "unknown" part of the process. I'd start drafting its implementation ASAP. This could put some additional requirements on the proving (e. g. processing assertions, pre-, post-conditions, encoding collection/other ops, etc.).

**Comment by aslesarenko** [comment]
Consider moving the text above into document and create a PR.
This will be easier to collaborate.

**Comment by aslesarenko** [comment]
I think the roadmap items in the description would be useful.
