### ISSUE TITLE
Define default size for all type (Coster, ByIndex)

### ISSUE THREAD

**Issue by greenhat** [ScorexFoundation/sigmastate-interpreter#628]
Discovered while working on https://github.com/ScorexFoundation/sigmastate-interpreter/pull/617#issuecomment-568504083 
In the following code: 
```
    (HEIGHT > deadline && pkA) || {
      (OUTPUTS.nonEmpty && OUTPUTS(0).R4[Coll[Byte]].isDefined) && {
        val tokens = OUTPUTS(0).tokens
        val tokenDataCorrect = tokens.nonEmpty &&
          tokens(0)._1 == tokenId &&
          tokens(0)._2 >= tokenAmount

        val knownId = OUTPUTS(0).R4[Coll[Byte]].get == SELF.id
        // TODO fix Coll.fromItems crashing Inox typer and rewrite with allOf(Coll.fromItems[Boolean](
        tokenDataCorrect &&
          OUTPUTS(0).propositionBytes == pkA.propBytes &&
          knownId
      }
    }
```
http://github.com/ScorexFoundation/sigmastate-interpreter/blob/e3739378b2f5f0b1859c6f950566173314bf3140/contract-verification/src/main/scala/sigmastate/verification/contract/AssetsAtomicExchange.scala#L18-L32
Coster crashes if box tokens are empty in `tokens(0)` although `&&` is lazy and false `tokens.nonEmpty` should prevent from evaluating the rest. 

>But because costing has to be done for both sides, it is not lazy. So the right side should not reduce the domain (область определения) of the contract, and this will require to have some reasonable approximations.

The relevant part in coster - http://github.com/ScorexFoundation/sigmastate-interpreter/blob/e3739378b2f5f0b1859c6f950566173314bf3140/sigmastate/src/main/scala/sigmastate/eval/RuntimeCosting.scala#L1494-L1494

We need to define default size for all types.

**Comment by greenhat** [comment]
Experienced also in seller's contract:
```
    (HEIGHT > deadline && pkB) || (
      OUTPUTS.size > 1 &&
        OUTPUTS(1).R4[Coll[Byte]].isDefined
      ) && {
      val knownBoxId = OUTPUTS(1).R4[Coll[Byte]].get == SELF.id
      OUTPUTS(1).value >= ergAmount &&
        knownBoxId &&
        OUTPUTS(1).propositionBytes == pkB.propBytes
    }
```
in http://github.com/ScorexFoundation/sigmastate-interpreter/blob/59b3269752670fd5c184c65c542d7a18b78c1ad1/contract-verification/src/main/scala/sigmastate/verification/contract/AssetsAtomicExchange.scala#L34-L46

`OUTPUTS(1)` cause exception in costing when there is only one out box when testing for `(HEIGHT > deadline && pkB)` in [test](http://github.com/ScorexFoundation/sigmastate-interpreter/blob/59b3269752670fd5c184c65c542d7a18b78c1ad1/sigma-dsl-compiler-macros-playground/src/test/scala/sigmastate/verification/test/AssetsAtomicExchangeCompilationTest.scala#L241-L241)

**Comment by aslesarenko** [comment]
This is not necessary for JIT costing.
