### ISSUE TITLE
Move certified contracts and ErgoScala compiler projects into a separate repos

### ISSUE THREAD

**Issue by greenhat** [ScorexFoundation/sigmastate-interpreter#642]
### Motivation 
Lacking Scala 2.11 support (essential to use Sigma in Appkit);

### Implementation
1. Move `sigmaDslCompilerMacros`(ErgoScala compiler), `sigmaDslCompilerMacrosPlayground` from #617  to a new repo `ergoplatform/ergo-scala-compiler` .
2. Move `verifiedContracts` from #617 to a new repo `ergoplatform/ergo-contracts`.
2. Merge(close) #617 .

**Comment by aslesarenko** [comment]
Yes, Scala 2.11 is the requirement to run sigma on Android. And also to run it in the browser in future we need to be conservative with using fancy tech.

**Comment by greenhat** [comment]
Done.
https://github.com/ergoplatform/ergo-scala-compiler
https://github.com/ergoplatform/ergo-contracts/
