### ISSUE TITLE
Add fromBase16 to the frontend

### ISSUE THREAD

**Issue by kushti** [ScorexFoundation/sigmastate-interpreter#649]
UPD by @aslesarenko 
Currently `fromBase58` and `fromBase64` global compile-time functions are implemented.
The functions can only accept string literals and transform them into ByteArrayConstant tree nodes at compile time.
The new function `formBase16` should be added [here](https://github.com/ScorexFoundation/sigmastate-interpreter/blob/e776b81605a65db3ec06f60b0105d7a9264c34f5/sigmastate/src/main/scala/sigmastate/lang/SigmaPredef.scala#L187).
And the corresponding test added to  `property("fromBaseX")` test case.

Currently only fromBase58 exists, which is not convenient in many cases. Add fromBase16 to the frontend.

**Comment by thub1271** [comment]
Hello, I was trying to add my first pull request for this ticket but seem to not have access? Is there some special way to ask for access? Thanks!

**Comment by MrStahlfelge** [comment]
Everyone can open a pull request, but you need to use your own fork to push to. [See here](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request)
