### ISSUE TITLE
DeserializeContext not supported

### ISSUE THREAD

**Issue by jasondavies** [ScorexFoundation/sigmastate-interpreter#655]
```
sigmastate.lang.exceptions.CosterException: Don't know how to evalNode(DeserializeContext(1,SSigmaProp))
```

This happens when attempting to test `Pay2SHAddress` or just a simple script that attempts to do:

```
DeserializeContext(1, SSigmaProp)
```

The above exception seems to occur in `evalNode` in `RuntimeCosting`.

**Comment by greenhat** [comment]
That's weird. Could you provide the details on how I can reproduce it? 
`DeserializeContext` node should be substituted to the extracted script before the costing stage. See https://github.com/ScorexFoundation/sigmastate-interpreter/blob/63fa84e989df7ac5f19f809dae340d7f63e755ab/sigmastate/src/main/scala/sigmastate/interpreter/Interpreter.scala#L104-L112

**Comment by jasondavies** [comment]
Ah, that kind of makes sense.  I'm using `executeWithContext` for testing, but modified to work on compiled ErgoTree.  The tree I'm using is:

```00ea0208cd0355e3409b35892e2b916a6362a93f742d06ce1726e2eaa688738b34b652d1142ad40800```

Which should be:

```
val scriptIsCorrect = DeserializeContext(0, SSigmaProp)
val tree = ErgoTree.withoutSegregation(SigmaAnd(ProveDlog(alice), scriptIsCorrect))
```

But if the `DeserializeContext` node is only substituted by the interpreter during verification, I guess my modified `executeWithContext` needs to do that too before `reduceToCrypto`.

**Comment by jasondavies** [comment]
OK, this is more of a problem with JSON (de)serialisation, but I think it won't allow scripts to be deserialised in the context extension:

```
The request content was malformed:
java.lang.ClassCastException: class sigmastate.EQ cannot be cast to class sigmastate.Values$EvaluatedValue (sigmastate.EQ and sigmastate.Values$EvaluatedValue are in unnamed module of loader 'app'): DownField(0),DownField(extension),DownField(context)
```
