### ISSUE TITLE
Inconsistent "%" semantics for BigInt

### ISSUE THREAD

**Issue by kushti** [ScorexFoundation/sigmastate-interpreter#698]
In SigmaDSL, "%" is a synonym for mod:

@Internal def %(m: BigInt): BigInt = mod(m)

while in NumericOps.scala "%"  is a synonym for "rem" :

 /** Descriptor of binary `%` operation (reminder of integral division). */
case class IntegralMod[T](i: ExactIntegral[T])(implicit elem: Elem[T]) extends DivOp[T]("%", i) {
    /** Note, this is implemented using `ExactIntegral.rem` method which delegates to
      * `scala.math.Integral.rem`. The later also implements `%` operator in Scala for
      * numeric types.
      * @see sigmastate.eval.NumericOps.BigIntIsIntegral
      */
    override def applySeq(x: T, y: T): T = i.rem(x, y)
  }

This looks confusing, we have different semantics for "%" around the repository ?

**Comment by aslesarenko** [comment]
@kushti I think this `@see sigmastate.eval.NumericOps.BigIntIsIntegral` is wrong here, because this `IntegralMod` class is not used for BigInt at all.

**Comment by aslesarenko** [comment]
Resolved in #742
