### ISSUE TITLE
Typecast operations

### ISSUE THREAD

**Issue by catena2w** [ScorexFoundation/sigmastate-interpreter#70]
- [x] Implement operations on top of BigInt
- [ ] (?) Unsigned int type
- [ ] Type casts

**Comment by kushti** [comment]
@ergomorphic what's the status?

**Comment by ergomorphic** [comment]
@kushti Which typecasts we may need other than what we already have for numeric types (i.e. byte.toInt, int.toByte, etc)? 
All these operations are represented in ErgoTree using Upcast and Downcast nodes.
Do we need other than that?
