### ISSUE TITLE
Introduce a new limit on structural depth of data values

### ISSUE THREAD

**Issue by kushti** [ScorexFoundation/sigmastate-interpreter#749]
corresponds to todo: "TODO v5.0: introduce a new limit on structural depth of data values" in DataValueComparer

UPDATE (@aslesarenko): 
The goal is to prevent instantiation of complex intermediate values.
Then comparing them will never be an issue.

**Comment by aslesarenko** [comment]
The limit is not required, the problem is prevented automatically by JIT costing. See description for the method https://github.com/ScorexFoundation/sigmastate-interpreter/blob/89713cd33c17a9c50c408941e28c8dc58f0e0615/sigmastate/src/main/scala/sigmastate/DataValueComparer.scala#L316
