### ISSUE TITLE
Control maxTreeDepth in serialize (same as in deserialize)

### ISSUE THREAD

**Issue by aslesarenko** [ScorexFoundation/sigmastate-interpreter#781]
This should be done in:
- [ ] DataSerializer
- [ ] SigmaBoolean.serializer
- [ ] ValueSerializer

Key requirement: both deserialize and serialize either both work or both fail on the same data.

**Comment by darkdrag00n** [comment]
Hi @aslesarenko, is this issue still relevant? Looks like #798 is abandoned. I am willing to create a new PR based on it and drive it to completion if needed. Do let me know

**Comment by jozanek** [comment]
Hey guys, not sure what abandoned means in this context but it is definitely ready to be reviewed again and/or merged.

**Comment by darkdrag00n** [comment]
Ah ok, thanks for the update @jozanek

**Comment by aslesarenko** [comment]
@darkdrag00n, I down graded this issue and removed bounty label. 
I've also put the PR in draft.
The main reason is this issue solves non existent problem.
The depth limit was initially added to Reader in order to prevent attacks, but actually we have hard limit on the size of every ErgoBox 4K bytes. So, basically doesn't matter what has been put in the box as long as it is < 4K.
With new JIT interpreter this becomes even less important. 

Also, both serializers and deserializers are part of network consensus, which put any changes under strict scrutiny.
Any change should come with a proof that it doesn't break the consensus (i.e. there is no situation when the new version behaves differently from a previous version).

For this reason it is better to keep them as simple as possible.
