### ISSUE TITLE
Add isEmpty method to frontend compiler

### ISSUE THREAD

**Issue by kushti** [ScorexFoundation/sigmastate-interpreter#782]
example:
```
box.R3[Int].isEmpty // check that value of R3 is undefined
```

**Comment by kettlebell** [comment]
I'm looking into this one. I wonder if this is already covered with `SOption.isDefined` (A.15.1 in ergotree.pdf)?

**Comment by darkdrag00n** [comment]
Hi @kushti , @aslesarenko. I am looking to get involved in this project. Can I pick this up?

**Comment by aslesarenko** [comment]
@darkdrag00n, yes, should I assign it to you?

**Comment by darkdrag00n** [comment]
Yes, please. Thanks!
