### ISSUE TITLE
ContractTemplate data structure according to EIP5

### ISSUE THREAD

**Issue by aslesarenko** [ScorexFoundation/sigmastate-interpreter#851]
**Goal:**
To implement representation of templates, serialization and generation of ErgoTree from template by substituting parameters.

**Non-goal:**
Implement compiler from source code to template representation.

- [ ] define ContractTemplate classes, serializers and JSON encoders according to EIP
- [ ] cover with unit tests
- [ ] implement applyTemplate(p1, p2, p3) -> ErgoTree
- [ ] cover `applyTemplate` method with tests

**Comment by darkdrag00n** [comment]
I am starting to take a look at this

**Comment by darkdrag00nv2** [comment]
Started looking into this.

**Comment by darkdrag00nv2** [comment]
@aslesarenko Have a question regarding the `applyTemplate` implementation.

Consider a ContractTemplate defined with 3 parameters. Suppose the `constValues = [Some(1), None, Some(100)]` i.e the first and third parameter has default values defined.

In `applyTemplate(...)`, do we want to require all the 3 values or do we also want to allow cases where only second constant (which doesn't have a default value) is strictly required and optionally different values for first and second constants can be provided as an override?

**Comment by aslesarenko** [comment]
> ... or do we also want to allow cases where only second constant (which doesn't have a default value) is strictly required and optionally different values for first and second constants can be provided as an override?

Yes, I was thinking about this approach.
The output of applyTemplate should be valid ErgoTree, which means every ConstantPlaceholder in the body should refer to somehow defined constant. So if the constant have the default, then it can be omitted in the parameters of applyTemplate. Override will also be useful. 
This flexibility will however rise the question of how we will define equality between templates as we can do it in different ways.
