### ISSUE TITLE
SByteArray is not a collection

### ISSUE THREAD

**Issue by catena2w** [ScorexFoundation/sigmastate-interpreter#87]
Now it's not possible to work with SByteArray as with collection, e.g. this code does not compile:
```
EQ(SizeOf(ExtractRegisterAs[SByteArray.type](Self, R4)), bitsInString)
```

Relates to https://github.com/ScorexFoundation/sigmastate-interpreter/issues/71

**Comment by kushti** [comment]
Well, we don't have Byte type to make conversions
