### ISSUE TITLE
Extract collection from register

### ISSUE THREAD

**Issue by catena2w** [ScorexFoundation/sigmastate-interpreter#88]
I can't find an example of collection extraction from a register, and expected way to do this like `ExtractRegisterAs[SCollection[Boolean]](Self, R4)(SCollection[Boolean])` does not work

**Comment by kushti** [comment]
it shouldn't work also, as it is impossible to define collection size (i.e. cost) before transformations

**Comment by catena2w** [comment]
Some sort of user-defined collections is required. E.g. If we want AVLTreeModification operation, user (not a script) should provide collection of modifications and proof for them.
