### ISSUE TITLE
[JS] Make `ValueObj.fromHex()` to accept any valid constant bytes

### ISSUE THREAD

**Issue by arobsn** [ScorexFoundation/sigmastate-interpreter#899]
Adding support to any valid constant in `ValueObj.fromHex()` is specially helpful to test new serializer implementations.

Currently, I have an implementation of all Tuple types in `@fleet-sdk/serializer` but I'm not able to test specific cases like tuples with 4 and 4+ items.

**Comment by aslesarenko** [comment]
ValueObj.fromHex can deserialise any hex produced from ConstantSerializer.
