### ISSUE TITLE
Potential problem with type casts in ProverInterpreter

### ISSUE THREAD

**Issue by ergomorphic** [ScorexFoundation/sigmastate-interpreter#90]
In the following line of `ProverInterpreter.prove`

`val step4 = simulations(step3).get.asInstanceOf[UnprovenTree]`

when `simulations` is executing the following case:

```
case su: UnprovenSchnorr =>
     if (su.simulated) {
       assert(su.challengeOpt.isDefined)
       SchnorrSigner(su.proposition, None).prove(su.challengeOpt.get)
     } else {
       val (r, commitment) = DLogInteractiveProver.firstMessage(su.proposition)
       su.copy(commitmentOpt = Some(commitment), randomnessOpt = Some(r))
     }
```

if su.simulated == true, `prove` will return  `UncheckedTree`, and there will be type cast error

**Comment by ergomorphic** [comment]
@kushti Could you please check if it still make sense and close if it is not.

**Comment by aslesarenko** [comment]
Seems like we don't have this code anymore
