### ISSUE TITLE
SigmaTemplateCompiler (EIP-5) does not take non-parameter constants into account

### ISSUE THREAD

**Issue by Luivatra** [ScorexFoundation/sigmastate-interpreter#966]
Take the following example into account:
`
@contract isItTime(theTime: Long) = {
  sigmaProp(
    theTime > CONTEXT.preHeader.timestamp &&
    1000L < CONTEXT.preHeader.timestamp
  )
}
`

Following issues occur:

1. TyperException: Cannot assign type for variable 'theTime' because it is not found in env Map
~~2. The resulting ContractTemplate (assuming issue 1 is fixed) only contains the parameter constant (naturally with index 0) but not the other constants present in the contract (such as in this case LongConstant(1000)).~~

**Comment by Luivatra** [comment]
Perhaps solving issue# 1 would be enough if it can be replaced with a ConstantPlaceholder because constantsegregation isnt performed.

**Comment by aslesarenko** [comment]
@Luivatra, the issue#2 is by design. Why do you want other constants to be segregated?

**Comment by Luivatra** [comment]
> @Luivatra, the issue#2 is by design. Why do you want other constants to be segregated?

I don't, I just didn't realize that it worked like that, actually love that those are not segregated (some of the Paideia contracts have a LOT of constants) Let me cross it out.

**Comment by aslesarenko** [comment]
@ross-weir, could you please look into this?
