### ISSUE TITLE
Add new PolyMethodCall node with type parameters

### ISSUE THREAD

**Issue by aslesarenko** [ScorexFoundation/sigmastate-interpreter#980]
## Problem
Current MethodCalls are limited (see this [ScalaDoc](https://github.com/ScorexFoundation/sigmastate-interpreter/blob/20ed01d5ae78f018d52415773cc4e39b031edf86/data/shared/src/main/scala/sigma/serialization/MethodCallSerializer.scala#L35))
In particular they cannot be used to represent `CONTEXT.getVar[Int](1).get` or `box.getReg[Long](5).get`, because the type parameter `Int` and `Long` respectively cannot be serialized in v5.0.

## Solution

- Add a new ErgoTree node `PolyMethodCall` with a new opcode which works exactly as MethodCall, but supports 1 or more type parameters. 
- The PolyMethodCall nodes would be introduced in ErgoTree by ErgoScript compiler when necessary, i.e. then concrete types parameters need to be specified.
- The type parameters should be concrete types which are supported by TypeSerializer.

**Comment by kushti** [comment]
I don't think the new node is needed: 

* MethodCallSerializer structurally is ready for type substitution, it is just always `Map.empty` now, but for new method you can fix that
* Code for PolyMethodCall(Serializer) will mostly repeat the MethodCall(Serializer), abstraction would bring more complexity
* Versioning-wise adding new node & serializer is more complex
* New opcode will be introduces, which is also more complex (and there were few bugs already with introducing new ids)

So looks like unnecessary complication

**Comment by kushti** [comment]
For performance, you can add a flag to polymorphic methods, and do just one check during deserialization then, and then do other checks only for polymorphic methods

**Comment by aslesarenko** [comment]
> you can add a flag to polymorphic methods

Ok, make sense.
