### ISSUE TITLE
ByIndex problems

### ISSUE THREAD

**Issue by catena2w** [ScorexFoundation/sigmastate-interpreter#99]
- [x] index should not be Scala Int. `Value[SInt.type]` expected
- [ ] default value may me useful

relates to #87, #88, #98

**Comment by greenhat** [comment]
I'd like to tackle this one.

**Comment by catena2w** [comment]
Check default value for `ExtractRegisterAs` operation - logically it's the same `ByIndex` operation where collection is predefined and contains output registers

**Comment by greenhat** [comment]
@catena2w that is actually what pushed me to have this questions in the first place. :) In `ExtractRegisterAs` the syntax for with/without default value is consistent methods `valueOrElse(defaultValue)` vs `value`. When for `ByIndex` a more consistent approach would probably be `Collection(index)` vs `Collection(index, defaultValue)`. I just found it lacking a bit readability and discoverability so I thought that method `getOrDefault(index, defaultValue)` might suit better. But consistency is probably more important here so l suggest we go with "apply" syntax `Collection(index, defaultValue)`. Does it make any sense?

**Comment by kushti** [comment]
@catena2w @greenhat we can avoid default  here
